### ISSUE TITLE
Crash when resizing in rules demo

### ISSUE THREAD

**Issue by ghost** [cropleyb/pentai#77]
On Linux

```
[02:15:33.223][WARNING][stderr: Traceback (most recent call last):]
[02:15:33.224][WARNING][stderr:   File "/home/terje/pentai/startup.py", line 43, in run]
[02:15:33.224][WARNING][stderr:     pa.run()]
[02:15:33.225][WARNING][stderr:   File "/home/terje/kivy/kivy/app.py", line 825, in run]
[02:15:33.227][WARNING][stderr:     runTouchApp()]
[02:15:33.228][WARNING][stderr:   File "/home/terje/kivy/kivy/base.py", line 484, in runTouchApp]
[02:15:33.230][WARNING][stderr:     EventLoop.window.mainloop()]
[02:15:33.231][WARNING][stderr:   File "/home/terje/kivy/kivy/core/window/window_pygame.py", line 381, in mainloop]
[02:15:33.232][WARNING][stderr:     self._mainloop()]
[02:15:33.233][WARNING][stderr:   File "/home/terje/kivy/kivy/core/window/window_pygame.py", line 356, in _mainloop]
[02:15:33.233][WARNING][stderr:     self._size = event.size]
[02:15:33.234][WARNING][stderr:   File "properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy/properties.c:4252)]
[02:15:33.235][WARNING][stderr:   File "properties.pyx", line 672, in kivy.properties.ListProperty.set (kivy/properties.c:9416)]
[02:15:33.238][WARNING][stderr:   File "properties.pyx", line 409, in kivy.properties.Property.set (kivy/properties.c:4727)]
[02:15:33.239][WARNING][stderr:   File "properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5259)]
[02:15:33.243][WARNING][stderr:   File "_event.pyx", line 1055, in kivy._event.EventObservers.dispatch (kivy/_event.c:10636)]
[02:15:33.245][WARNING][stderr:   File "properties.pyx", line 1302, in kivy.properties.AliasProperty.trigger_change (kivy/properties.c:19831)]
[02:15:33.249][WARNING][stderr:   File "properties.pyx", line 1308, in kivy.properties.AliasProperty.trigger_change (kivy/properties.c:19724)]
[02:15:33.250][WARNING][stderr:   File "properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5259)]
[02:15:33.250][WARNING][stderr:   File "_event.pyx", line 1055, in kivy._event.EventObservers.dispatch (kivy/_event.c:10636)]
[02:15:33.251][WARNING][stderr:   File "/home/terje/pentai/pentai/gui/scale.py", line 13, in set_height]
[02:15:33.251][WARNING][stderr:     self.dp = height / 720.0]
[02:15:33.252][WARNING][stderr:   File "properties.pyx", line 377, in kivy.properties.Property.__set__ (kivy/properties.c:4252)]
[02:15:33.252][WARNING][stderr:   File "properties.pyx", line 409, in kivy.properties.Property.set (kivy/properties.c:4727)]
[02:15:33.252][WARNING][stderr:   File "properties.pyx", line 460, in kivy.properties.Property.dispatch (kivy/properties.c:5259)]
[02:15:33.252][WARNING][stderr:   File "_event.pyx", line 1031, in kivy._event.EventObservers.dispatch (kivy/_event.c:10313)]
[02:15:33.253][WARNING][stderr:   File "/home/terje/kivy/kivy/lang.py", line 1441, in call_fn]
[02:15:33.253][WARNING][stderr:     element, key, value, rule.value))]
[02:15:33.253][WARNING][stderr: ReferenceError: weakly-referenced object no longer exists]
saving traceback to /home/terje/.config/pentai/err.txt

```

**Comment by cropleyb** [comment]
Thanks for that :)
For the record, I had actually implemented a workaround for this, and just hadn't pushed it to github yet.
